version: '1'
services:
  frontend:
    build: ./frontEnd/
    container_name: frontEnd
    depends_on:
      - backend
    ports:
      - '3000:3000'
  backend:
    build: ./backEnd/
    container_name: backEnd
    depends_on:
      - database
    expose:
      - 8080
    ports:
      - '8080:8080'
  database:
    image: mongo
    container_name: database
    restart: always
    volumes:
      - mongo-data:/data/db
      - /etc/timezone:/etc/timezone:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"

volumes:
  mongo-data:
    driver: local
